module.exports = {
  enums: {
    quoteStatus: ["DRAFT", "PENDING_APPROVAL", "PENDING_EFFECTIVE", "ACTIVE", "REJECTED_PENDING_EDIT", "EXPIRED"],
    approvalStatus: ["PENDING", "IN_PROGRESS", "APPROVED", "REJECTED"],
    rebateType: ["AMOUNT", "RATE"],
    belowCostMode: ["STRICT", "WARNING"],
    warningLevel: ["NONE", "YELLOW", "RED"],
    userRole: ["SALES_ENTRY", "SALES_MANAGER", "BUSINESS_HEAD", "FINANCE_HEAD", "SYSTEM_ADMIN"],
  },
  customer: [
    "id",
    "customer_code",
    "customer_name",
    "customer_level",
    "customer_type",
    "channel_type",
    "region",
    "default_discount",
    "default_rebate_value",
    "default_rebate_type",
    "default_approver_id",
    "status",
    "remark",
    "created_at",
    "updated_at",
  ],
  product: [
    "id",
    "sku",
    "product_name",
    "product_series",
    "product_model",
    "variant",
    "launch_date",
    "default_msrp",
    "default_cost",
    "default_formula_id",
    "channel_factor",
    "status",
    "remark",
    "created_at",
    "updated_at",
  ],
  pricing_formula: [
    "id",
    "formula_code",
    "formula_name",
    "formula_version",
    "formula_expression",
    "applicable_customer_type",
    "applicable_product_series",
    "applicable_channel_type",
    "allow_below_cost_draft",
    "status",
    "effective_from",
    "effective_to",
    "created_by",
    "created_at",
    "updated_at",
    "remark",
  ],
  quote: [
    "id",
    "quote_no",
    "customer_id",
    "product_id",
    "formula_id",
    "msrp",
    "cost_price",
    "discount_factor",
    "special_discount",
    "rebate_value",
    "rebate_type",
    "temporary_support",
    "channel_factor",
    "effective_month",
    "effective_from",
    "effective_to",
    "tax_rate",
    "final_quote_price",
    "gross_profit",
    "gross_margin",
    "warning_level",
    "warning_message",
    "below_cost_flag",
    "approval_required_flag",
    "approval_status",
    "quote_status",
    "formula_version_snapshot",
    "calculation_steps",
    "remark",
    "created_by",
    "created_at",
    "updated_at",
  ],
  quote_approval: [
    "id",
    "approval_no",
    "quote_id",
    "approval_type",
    "current_node",
    "approver_id",
    "approver_name",
    "approval_status",
    "approval_comment",
    "initiated_by",
    "initiated_at",
    "approved_at",
    "created_at",
    "updated_at",
  ],
  quote_approval_node: [
    "id",
    "approval_id",
    "node_order",
    "node_name",
    "approver_id",
    "approver_name",
    "approval_status",
    "approval_comment",
    "approved_at",
  ],
  price_change_log: [
    "id",
    "business_type",
    "target_id",
    "action_type",
    "before_data",
    "after_data",
    "operator_id",
    "operator_name",
    "operation_time",
    "device_info",
  ],
};
